name: buildVersion bump for electron-builder
description: Automated build version bump for electron-builder.
branding:
  icon: chevron-up
  color: blue
inputs:
  path:
    description: "Path of package.json"
    default: "./"
  descriptor:
    description: "Descriptor for buildVersion (staging, wip, etc.)"
    default: ""
outputs:
  version:
    description: "New buildVersion for bundle"
runs:
  using: "node12"
  main: "index.js"