name: test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install dependencies
      run: npm install

    - name: Local action test
      uses: ./
      id: version

    - name: Get version
      run: echo "Version is ${{ steps.version.outputs.version }}"